[package]
org = "user"
name = "Back_End_Ballerina"
version = "0.1.0"
distribution = "2201.10.3"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"